env:
    - DEFINITION=5.2.17 PHP_BUILD_CONFIGURE_OPTS="--with-libdir=lib/x86_64-linux-gnu"
    - DEFINITION=5.3.3 PHP_BUILD_CONFIGURE_OPTS="--with-libdir=lib/x86_64-linux-gnu"
    - DEFINITION=5.3.29
    - DEFINITION=5.4.45
    - DEFINITION=5.5.29
    - DEFINITION=5.6.13
    - DEFINITION=7.0.0RC3

script: ./run-tests.sh $DEFINITION

before_install:
    - sudo apt-get update -qq
    - sudo apt-get build-dep php5-cli
    - sudo apt-get install -qq git-core libmcrypt-dev libjpeg-dev libreadline-dev

before_script:
    - git clone http://github.com/sstephenson/bats
    - bats/install.sh $HOME
    - export PATH=$HOME/bin:$HOME/libexec:$PATH
    - bats --version

after_failure:
    - sudo cat $(ls -r /tmp/php-build*.log | head -n 1)
