env:
    - DEFINITIONS=stable

script: ./run-tests.sh $DEFINITIONS

before_script:
    - git clone http://github.com/sstephenson/bats
    - bats/install.sh $HOME
    - export PATH=$HOME/bin:$HOME/libexec:$PATH